[package]
name = "fitting_engine_macros"
version = "0.1.0"
authors = ["Lucca Kaasgaard Christiansen <1078059@ucn.dk>", "Alexandra Ã˜stermark <alex.cramt@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.6"
quote = "1.0"
proc-macro2 = "1.0.24"
